### ISSUE TITLE
Side-effects related to libpointmatcher

### ISSUE THREAD

**Issue by danieldugas** [ethz-asl/gtsam_catkin#24]
Note: This is a really strange one and I'm still looking at possible ways I might have done something wrong. Still, after this much testing It seems like an issue might be in order.

Environment:
- Ubuntu 16.04
- gtsam_catkin currently on master, commit 4b61d68
- using catkin build
- ros-kinetic-desktop-full is installed

Behavior:
- added gtsam_catkin as dependency to a small ros package project, in both package.xml and CMakeLists.txt
- compile with catkin : ```fatal error: gtsam/nonlinear/ISAM2.h: No such file or directory```

Steps taken:
- check that package.xml contains gtsam_catkin dependency
- recheck CMakeLists.txt : find_package(catkin REQUIRED COMPONENTS ... gtsam_catkin) is there, no issue with other packages listed.
- ```include_directories(include ${catkin_INCLUDE_DIRS})``` is also there and headers for other packages are being found correctly.
- checked that ISAM2.h was indeed in devel/include/gtsam/nonlinear/ : it was.
- added devel/include to include_directories manually: deeper dependencies error between gtsam and Eigen (did not investigate further, sorry)
- Switched to catkin simple: same behavior observed.
- Switched to new workspace, add only minimal dependencies: same behavior.
- Found a functioning project with dependency on gtsam_catkin, copy header include lines, CMakeLists.txt lines from project, and package.xml lines which relate to gtsam_catkin: same behavior
- Create minimal project with the following three files in a new workspace:

test_proj/CMakeLists.txt:
```
cmake_minimum_required(VERSION 2.8.3)
project(test_proj)

add_definitions(-std=c++11)

find_package(catkin_simple 0.1.0 REQUIRED)
catkin_simple(ALL_DEPS_REQUIRED)

cs_add_executable(test_proj_exe test_proj.cpp)

cs_install()
cs_export()
```

test_proj/package.xml:
```
<?xml version="1.0"?>

<package format="2">
  <name>test_proj</name>
  <version>0.0.1</version>
  <description>WIP</description>

  <author email="dugasd@ethz.ch">Daniel Dugas</author>
  <maintainer email="dugasd@ethz.ch">Daniel Dugas</maintainer>

  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <buildtool_depend>catkin_simple</buildtool_depend>
  <depend>gtsam_catkin</depend>

</package>
```

test_proj/test_proj.cpp:
```
#include <gtsam/nonlinear/ISAM2.h>

int main(int argc, char **argv) {
}
```

after cloning  gtsam_catkin and catkin_simple to the workspace, the same error is shown:
```fatal error: gtsam/nonlinear/ISAM2.h: No such file or directory```

- After a process of elimination, working from the working repository, the observed fix is as follows:
add a single line to test_proj/package.xml : 
```
  <depend>libpointmatcher</depend>
```
and clone libpointmatcher to the workspace.

Compilation is then successful. I also applied the same fix to my own project and also immediately observed successful compilation. Any thoughts?

**Comment by danieldugas** [comment]
I've reproduced this error on another 16.04 machine.

[test_proj.zip](https://github.com/ethz-asl/gtsam_catkin/files/2196858/test_proj.zip)

**Comment by HannesSommer** [comment]
Thanks @danieldugas  for the deep digging. The gtsam_catkin's CMakeLists.txt & gtsam-extra.cmake were incomplete such that they didn't export the `${CATKIN_DEVEL_PREFIX}/include` as include folder despite this being the place where it gets installed to. 
The libpointmatcher "sideeffect" was to rightfully export this include folder because it is also installing to it.

By lucky coincidence @eggerk recently solved this with the already merged PR #26  (as a cleanup component). Hence, current master should behave nicer in this respect. However, it also comes with a new catkin dependency (https://github.com/ethz-asl/metis_catkin).

**Comment by danieldugas** [comment]
Thanks @HannesSommer , it is indeed fixed!

**Comment by danieldugas** [comment]
I indeed had looked at the feature/install branch during my digging, but noticing the extra dependency and unsure as to which direction the branch was headed, I opted to remain on master. Cheers!

**Comment by HannesSommer** [comment]
Great! Thanks for feeding back :).
